---
title: "A study of changes in short chain fatty acids (SCFA) in women during pregnancy whose children developed asthma"
author: 
  - Huang Lin$^1$
  - $^1$BCBB, NIEHS
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    toc: true
    theme: united
---

```{r setup, warning=FALSE, message=FALSE}
# rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE, comment = NA,
                      fig.width = 6.25, fig.height = 5)
options(qwraps2_markup = "markdown",
        qwraps2_frmt_digits = 2)

library(openxlsx)
library(tidyverse) 
library(CLME)
library(magrittr)
library(qwraps2)
library(ggprism)
library(ggsci)
library(ggpubr)
library(rstatix)
library(jtools)
# library(kableExtra)
# options(digits = 3)
```

```{r helper}
plot_box = function(data, group_lab, group_var, key_var, adjust_var, title, y.position, step.increase) {
  
  select_vars = function() {
    any_of(c(group_var, key_var, adjust_var))
  }
  df_fig = data %>%
    dplyr::select(select_vars()) %>%
    mutate(group = get(group_var), value = get(key_var))
  df_fig$group = factor(df_fig$group, ordered = FALSE)
  
  lm_formula = paste("value ~ group + ", paste(adjust_var, collapse = " + "))
  lm_fit = lm(as.formula(lm_formula), data = df_fig)
  df_p = data.frame(group1 = "No", group2 = "Yes",
                    p = summary(lm_fit)$coef[grepl("group", names(coef(lm_fit))), "Pr(>|t|)"]) %>%
    mutate(p = round(p, 2))
  
  bxp = ggboxplot(df_fig, x = "group", y = "value", color = "group",
                  add = "jitter", xlab = FALSE, ylab = FALSE, title = title) +
    stat_pvalue_manual(df_p, y.position = y.position, 
                       step.increase = step.increase, label = "p") +
    scale_color_npg(name = NULL) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          strip.background = element_rect(fill = "white"),
          legend.position = "bottom",
          plot.title = element_text(hjust = 0.5))
  return(bxp)
}

plot_clme = function(clme_obj, group, y_min, y_max, p_gap, ann_pos, ...) {
  overall_p = clme_obj$p.value
  ind_p = clme_obj$p.value.ind
  est_mean = clme_obj$theta[group]
  est_se = sqrt(diag(clme_obj$cov.theta))[group]
  
  df_fig = data.frame(x = group, y = est_mean, err = est_se)
  df_p = data.frame(group1 = group[seq_len(length(group) - 1)],
                    group2 = group[-1],
                    x = group[-1],
                    label = paste0("p = ", round(ind_p, 3)),
                    y.position = seq.int(from = est_mean[2] + p_gap, 
                                         to = ifelse(est_mean[2] < max(est_mean), 
                                                     max(est_mean) + p_gap, 
                                                     max(est_mean) + 2 * p_gap), 
                                         length.out = length(group) - 1))
  df_ann = data.frame(x = group[1], y = ann_pos,
                      fill = "white",
                      label = paste0("Overall p-value = ", round(overall_p, 3)))
  
  fig = df_fig %>%
    ggplot(aes(x = x, y = y)) +
    geom_bar(stat = "identity", color = "black", aes(fill = x)) + 
    geom_errorbar(aes(ymin = y - 1.96 * err, ymax = y + 1.96 * err), 
                  width = .2, position = position_dodge(.9)) +
    add_pvalue(df_p,
               xmin = "group1",
               xmax = "group2",
               label = "label",
               y.position = "y.position",
               remove.bracket = FALSE, 
               ...) +
    geom_label(data = df_ann, aes(x = x, y = y, label = label), 
               size = 4, vjust = -0.5, hjust = 0, color = "black") +
    ylim(y_min, y_max) +
    theme_bw()
  return(fig)
}

lm_eqn = function(m){
  
  a = unname(coef(m))[1]
  b = unname(coef(m))[2]
  c = unname(coef(m))[3]
  p_val = summary(m)$coef[2, "Pr(>|t|)"]
  
  b = ifelse(sign(b) >= 0, 
             paste0(" + ", format(b, digits = 2)), 
             paste0(" - ", format(-b, digits = 2)))
  c = ifelse(sign(c) >= 0, 
             paste0(" + ", format(c, digits = 2)), 
             paste0(" - ", format(-c, digits = 2)))
  
  eq = substitute(paste(italic(y) == a, b, italic(x), c, italic(abx), ", ", italic(p) == p_val),
                  list(a = format(a, digits = 2), b = b, c = c,
                       p_val = format(p_val, digits = 2)))
  
  return(as.character(as.expression(eq)))              
}
```

# 1. Data description {.tabset}

## Import data

```{r}
df_meta = read.xlsx("../data/eager_scfa_samples_matched.xlsx")
df_meta$visit = recode(df_meta$visit, R = "20wks", S = "28wks")
df_meta$wheezing = recode(df_meta$wheezing, `0` = "No", `1` = "Yes")
df_meta$education = factor(df_meta$education,
                           levels = c("Not High-school graduate",
                                      "High-school graduate",
                                      "> High School"))

df_scfa_raw = read.xlsx("../data/Short-Chain Fatty Acid Analysis Result_Creative Proteomics_CPLC05192202-2.xlsx")

df_loq = df_scfa_raw[3:9, 13:14]
colnames(df_loq) = c("SCFA", "LOQ")

df_scfa = df_scfa_raw[-1, 1:12]
colnames(df_scfa) = c("Sample", "Barcode1", "Barcode2", "Box_Id", "Sample_Type",
                      "Acetic", "Propionic", "Isobutyric", "Butyric", 
                      "Isovaleric", "Valeric", "Hexanoic")
df_scfa = df_scfa %>%
  mutate_at(vars(Acetic:Hexanoic), as.numeric) %>%
  replace_na(list(Acetic = df_loq$LOQ[1]/2,
                  Propionic = df_loq$LOQ[2]/2,
                  Isobutyric = df_loq$LOQ[3]/2,
                  Butyric = df_loq$LOQ[4]/2,
                  Isovaleric = df_loq$LOQ[5]/2,
                  Valeric = df_loq$LOQ[6]/2,
                  Hexanoic = df_loq$LOQ[7]/2))

df_merge = df_meta %>%
  dplyr::left_join(df_scfa, by = c("Barcode1", "Barcode2", "Box_Id"))
df_v1 = df_merge %>%
  filter(visit == "20wks")
df_v2 = df_merge %>%
  filter(visit == "28wks")
```

## Data overview

```{r, results='asis'}
summary_template =
  list("Any report of asthma or wheezing since birth" =
       list("No" = ~ n_perc0(wheezing == "No", na_rm = TRUE),
            "Yes" = ~ n_perc0(wheezing == "Yes", na_rm = TRUE),
            "NA" = ~ n_perc0(is.na(wheezing))),
       "BMI" =
         list("min" = ~ round(min(BMI, na.rm = T), 2),
              "max" = ~ round(max(BMI, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(BMI, na_rm = T, show_n = "never")),
       "Age" =
         list("min" = ~ round(min(age, na.rm = T), 2),
              "max" = ~ round(max(age, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(BMI, na_rm = T, show_n = "never")),
       "Income" =
       list("Annual Less than $19,999" = ~ n_perc0(income == "1", na_rm = TRUE),
            "$20,000-$39,999" = ~ n_perc0(income == "2", na_rm = TRUE),
            "$40,000-$74,999" = ~ n_perc0(income == "3", na_rm = TRUE),
            "$75,000-$99,999" = ~ n_perc0(income == "4", na_rm = TRUE),
            "$100,000" = ~ n_perc0(income == "5", na_rm = TRUE),
            "NA" = ~ n_perc0(is.na(income))),
       "Fetus sex" =
       list("Female" = ~ n_perc0(sex_fetus1 == "2", na_rm = TRUE),
            "Male" = ~ n_perc0(sex_fetus1 == "1", na_rm = TRUE),
            "NA" = ~ n_perc0(is.na(sex_fetus1))),
       "Education" =
       list("Not High-school graduate" = ~ n_perc0(education == "Not High-school graduate", na_rm = TRUE),
            "High-school graduate" = ~ n_perc0(education == "High-school graduate", na_rm = TRUE),
            "> High School" = ~ n_perc0(education == "> High School", na_rm = TRUE),
            "NA" = ~ n_perc0(is.na(education))),
       "Acetic" =
         list("min" = ~ round(min(Acetic, na.rm = T), 2),
              "max" = ~ round(max(Acetic, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Acetic, na_rm = T, show_n = "never")),
       "Propionic" =
         list("min" = ~ round(min(Propionic, na.rm = T), 2),
              "max" = ~ round(max(Propionic, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Propionic, na_rm = T, show_n = "never")),
       "Isobutyric" =
         list("min" = ~ round(min(Isobutyric, na.rm = T), 2),
              "max" = ~ round(max(Isobutyric, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Isobutyric, na_rm = T, show_n = "never")),
       "Butyric" =
         list("min" = ~ round(min(Butyric, na.rm = T), 2),
              "max" = ~ round(max(Butyric, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Butyric, na_rm = T, show_n = "never")),
       "Isovaleric" =
         list("min" = ~ round(min(Isovaleric, na.rm = T), 2),
              "max" = ~ round(max(Isovaleric, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Isovaleric, na_rm = T, show_n = "never")),
       "Valeric" =
         list("min" = ~ round(min(Valeric, na.rm = T), 2),
              "max" = ~ round(max(Valeric, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Valeric, na_rm = T, show_n = "never")),
       "Hexanoic" =
         list("min" = ~ round(min(Hexanoic, na.rm = T), 2),
              "max" = ~ round(max(Hexanoic, na.rm = T), 2),
              "mean (sd)" = ~ qwraps2::mean_sd(Hexanoic, na_rm = T, show_n = "never"))
       )

df_summ1 = df_merge %>%
  summary_table(summary_template)
df_summ2 = df_merge %>%
  group_by(visit) %>%
  summary_table(summary_template)
cbind(df_summ2, df_summ1)
```

# 2. Two-group comparisons

SCFAs by the outcome variable (any report of asthma or wheezing since birth)

```{r, fig.width=14, fig.height=10}
var_list = c("Acetic", "Propionic", "Isobutyric", "Butyric", 
             "Isovaleric", "Valeric", "Hexanoic")
title_list = c("Acetic Acid", "Propionic Acid", "Isobutyric Acid", "Butyric Acid", 
               "Isovaleric Acid", "Valeric Acid", "Hexanoic Acid")
y_pos_list = c(6, 0.5, 0.1, 0.25, 0.09, 0.015, 0.1)
step_list = c(0.1, 0.1, 0.1, 0.1, 0.01, 0.005, 0.01)

bxp_list_v1 = list()
for (i in seq_along(var_list)) {
  bxp = plot_box(data = df_v1,
                 group_var = "wheezing",
                 key_var = var_list[i], 
                 adjust_var = c("BMI", "age", "income", "sex_fetus1", "education"),
                 title = title_list[i],
                 y.position = y_pos_list[i], 
                 step.increase = step_list[i])
  bxp_list_v1[[i]] = bxp
}

bxp_list_v2 = list()
for (i in seq_along(var_list)) {
  bxp = plot_box(data = df_v2,
                 group_var = "wheezing",
                 key_var = var_list[i], 
                 adjust_var = c("BMI", "age", "income", "sex_fetus1", "education"),
                 title = title_list[i],
                 y.position = y_pos_list[i], 
                 step.increase = step_list[i])
  bxp_list_v2[[i]] = bxp
}

p_box = ggarrange(bxp_list_v1[[1]], bxp_list_v1[[2]], bxp_list_v1[[3]], 
                  bxp_list_v1[[4]], bxp_list_v1[[5]], bxp_list_v1[[6]], bxp_list_v1[[7]], 
                  bxp_list_v2[[1]], bxp_list_v2[[2]], bxp_list_v2[[3]], 
                  bxp_list_v2[[4]], bxp_list_v2[[5]], bxp_list_v2[[6]], bxp_list_v2[[7]],
                  ncol = 7, nrow = 2, 
                  labels = c("a", "", "", "", "", "", "",
                             "b", "", "", "", "", "", ""), 
                  common.legend = TRUE)
p_box
ggsave("../figures/box_plot.jpeg", width = 14, height = 10, dpi = 100)
ggsave("../figures/box_plot.pdf", width = 14, height = 10)
```

# 3. Trend test

## Monotonic increasing trend {.tabset}

```{r, eval=FALSE}
cons = list(order = "simple", decreasing = FALSE, node = 1)
```

1. P-value is obtained by linear regression adjusting for antibiotics usage.

2. P-values were not adjusted for multiple comparisons.

### Acetate

```{r, eval=FALSE}
fit1 = clme(acetate_v1 ~ group1 + abx_use, data = df_v1, constraints = cons, seed = 123)
summ_fit1 = summary(fit1)

fig_ace = plot_clme(summ_fit1, group = c("g1", "g2", "g3", "g4"), 
                    y_min = 0, y_max = 4, p_gap = 0.7, ann_pos = 3.5)
fig_ace = fig_ace +
  scale_fill_npg(name = NULL) +
  labs(x = NULL, y = "Acetate")
fig_ace
ggsave("../images/scfa/primary_acetate.pdf", height = 5, width = 6.25)
ggsave("../images/scfa/primary_acetate.jpeg", height = 5, width = 6.25, dpi = 100)
```

# Session information

```{r, message = FALSE, warning = FALSE, comment = NA}
sessionInfo()
```



